### PR TITLE
[reconfiguration] unique key management

### PR DESCRIPTION
**Pull request by stonier**
Previously this ran into trouble using since the unique key was also the suffix'd name for the
client...and that suffix is not necessarily unique.

### CODE REVIEW

**Comment by stonier** [comment]
@naveedhd @AlexReimann the main difference here is that the namespace variable now must accept the full namespace (e.g. `/foo/troll/dudette`). The key now is for unique server management and only gets used to help build the dyn-recfg server namespace if no namespace is provided at all.

This will mean we'll have to update any reconfiguration yaml's with namespace variables to append the include the name to the namespace. e.g.

```
  dudette:
    module: feed_the_troll.cfg.DemoConfig
    namespace: /foo/troll
    overrides:
      double_param: 0.6
      str_param: Dudette
```

becomes:

```
  dudette:
    module: feed_the_troll.cfg.DemoConfig
    namespace: /foo/troll/dudette
    overrides:
      double_param: 0.6
      str_param: Dudette
```

**Comment by stonier** [comment]
If this is ok:
- @AlexReimann update the gopher reconfiguration nodes
- @naveedhd update the podium nodes
- @naveedhd accept the invite to this repo and merge this PR

**Comment by stonier** [comment]
Note: could not do something like

```
  /foo/troll/dudette:
    module: feed_the_troll.cfg.DemoConfig
    overrides:
      double_param: 0.6
      str_param: Dudette
```

Since the bloody param server goes and drops that parameterisation back at the root of the prameter server. That parameterisation is needed to be relative to the reconfiguration node itself so it knows where to find it.

**Comment by AlexReimann** [comment]
We go forward with this or?  

If so I will make a PR to bootstrap and navi (the standalone launchers use the troll)  

fyi:

``` yaml
$ cfind feed_the_troll | grep param_feeder | grep launch  

./desktop_ws/src/gopher_desktop/gopher_podium/launch/components/minimal.launch.xml:22:    <node pkg="feed_the_troll" type="param_feeder.py" name="podium_reconfiguration_feeder">
./navi_ws/src/gopher_motion_control/gopher_trajectory_controller/launch/standalone.launch:11:  <node if="$(arg reconfigure)" pkg="feed_the_troll" type="param_feeder.py" name="$(anon feeder)">
./bootstrap_ws/src/feed_the_troll/launch/demo_params_feeder.launch:5:    <node pkg="feed_the_troll" type="param_feeder.py" name="$(anon feeder)">
./bootstrap_ws/src/feed_the_troll/launch/demo_params.launch:7:    <node pkg="feed_the_troll" type="param_feeder.py" name="$(anon feeder)">
./bootstrap_ws/src/feed_the_troll/launch/demo_reconfiguration_feeder.launch:2:  <node pkg="feed_the_troll" type="param_feeder.py" name="$(anon feeder)">
./bootstrap_ws/src/gopher_common/gopher_bootstrap/launch/navigation/main.launch.xml:21:        <node pkg="feed_the_troll" type="param_feeder.py" name="$(anon feeder)">
```

**Comment by naveedhd** [comment]
Let's go forward with this. I will change in desktop.

**Pull request merged**
